version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: school 
      POSTGRES_PASSWORD: "school"
      POSTGRES_DB: school 
    ports:
    - "5432:5432"
    volumes:
    - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: